spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:p6spy:mysql://127.0.0.1:6033/mybatisplus
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  profiles:
    active: dev
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      logic-delete-field: flag  #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
## 日志配置
logging:
  config: src/main/resources/logback.xml
  level:
    top.xuwuruoshui.mybatisplus: info
